### ISSUE TITLE
assignments of Fuzzy C-mean

### ISSUE THREAD

**Issue by tkosaka1976** [JuliaStats/Clustering.jl#125]
I tired to use fuzzy_cmean and the function probably worked.
However, there are no-assignments or counts for FuzzyCMeansResult.
How can we get these values for each datasets?

**Comment by alyst** [comment]
Well, it's fuzzy, that's why no counts/assignments :)
But you are right, unfortunately there's no docs, so one would have to guess.
I'm not familiar with that code, but my guess is that `FuzzyCMeansResult.weights` (matrix of npoints × nclusters size) to retrieve fuzzy counts/assignments.
`res.weights[i, :]` should give you fuzzy assignments vector for i-th datapoint. `sum(res.weights, dim=1)` should give you the fuzzy point counts for each count.

**Comment by tkosaka1976** [comment]
I'd like to know how to calculate the belonging cluster of each data sets.
If you can, please explain it.
I'll consider to write a code.

**Comment by alyst** [comment]
Well, IIUC if `res = fuzzy_cmean(...)` then `res.weights[i, j]` should be the probability that `i`-th point belongs to the `j`-th cluster.
You can use e.g. `findmax(res.weights, dims=2)` to find for each point the highest probability and the corresponding cluster index.

Please note that github issues, in general, are not the right place for learning how to use the package. For these type of questions https://discourse.julialang.org/c/user or https://stackoverflow.com/questions/tagged/julia-lang would be much more appropriate (see also https://julialang.org/community/).
