### ISSUE TITLE
it seems that we need to make the distance matrix positive for the hierarchical clustering

### ISSUE THREAD

**Issue by jingpengw** [JuliaStats/Clustering.jl#133]
I tried to use `-similarityMatrix` and `maximum(similarityMatrix) .- similarityMatrix`, the result is very different. the minus version completely fails, but the other version which makes sure that the distance matrix values are all positive works.

**Comment by jingpengw** [comment]
I am using ward linkage.

the distance matrix in python should also be positive, this might be a reasonable requirement.

**Comment by alyst** [comment]
I guess Lance-Williams formula may break for certain linkage types (Ward? or all of them?) if the "distance" matrix is negative (for Ward negative distances make even less sense than for single/complete). I'm not sure `hclust()` should throw an error for negative distances (since it generates some result), but `@warn` would be nice (you're welcome to submit a PR).
