### ISSUE TITLE
DBSCAN DenseMatrix Requirement

### ISSUE THREAD

**Issue by maximilian-gelbrecht** [JuliaStats/Clustering.jl#153]
Hello,

Right now, if providing DBSCAN with a distance matrix, is has to be a `DenseMatrix` (or subtype of). I can't see a reason why one needs to be so strict here, it should be fine as long as there is a proper `view` function defined on the type. 

In particular, I tried using it with `PairwiseListMatrices` but of course there can also be other desirable situation where one does not want to hand over a DenseMatrix to the algorithm.

**Comment by alyst** [comment]
We have started to relax the input matrix requirements for some algorithms (#129, #138).
It could be, though, that for optimal performance DBSCAN relies on the input matrix being dense.
You are welcome to submit a PR, just make sure to measure the performance of DBSCAN with the original non-`DenseMatrix` vs the matrix converted to dense, so that we would not get surprising regressions.

**Comment by maximilian-gelbrecht** [comment]
ok, i dont have a lot of time this week, but i ll try to take at it next week.

**Comment by tlienart** [comment]
thanks to @oxinabox #193 will fix some of this too

**Comment by alyst** [comment]
Now `dbscan()` supports any `AbstractMatrix`, including the sparse ones.
