### ISSUE TITLE
Function dbscan does not accept keyword arguments 

### ISSUE THREAD

**Issue by neilpanchal** [JuliaStats/Clustering.jl#76]
Not sure if this is a Julia v0.5 issue:

I just installed Clustering and ran the following commands in the REPL:

```
using Clustering;
clusters= dbscan(randn(3,10000), 0.05, min_neighbors=3, min_cluster_size=20);

ERROR: function dbscan does not accept keyword arguments
in kwfunc(::Any) at .\boot.jl:236

```

**Comment by ararslan** [comment]
Can you post the output of `versioninfo(); Pkg.status("Clustering")`?

**Comment by neilpanchal** [comment]
@ararslan Sure. As follows:

```
Julia Version 0.5.0
Commit 3c9d753 (2016-09-19 18:14 UTC)
Platform Info:
  System: NT (x86_64-w64-mingw32)
  CPU: Intel(R) Xeon(R) CPU E5-2699 v3 @ 2.30GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, haswell)
 - Clustering                    0.6.0
```

**Comment by ararslan** [comment]
Ah, I see what the problem is. You're using the API as it stands on master, but that isn't implemented in Clustering v0.6.0. Looks like we should tag a new version of this package. In the meantime you should be able to get the desired functionality using `Pkg.checkout("Clustering", "master")`, then once a new version has been tagged, `Pkg.free("Clustering")`.

**Comment by neilpanchal** [comment]
@ararslan Thanks. That is working perfectly, I figured it was some release issue as well. Cheers!

**Comment by ararslan** [comment]
@neilpanchal Version 0.7.0 has been tagged, so you should be able to work from the release version again. Thanks for the report!
